# Generated by Django 5.0.6 on 2024-06-05 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toliq_name', models.CharField(max_length=50, unique=True)),
                ('phone_num', models.DecimalField(decimal_places=0, max_digits=13, unique=True)),
                ('telegram_link', models.CharField(max_length=41, unique=True)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='School.klass')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, unique=True)),
                ('about_teacher', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classes', models.ManyToManyField(related_name='teachers', to='School.klass')),
            ],
        ),
    ]
